---
title: "Publications"
subtitle: ""
---


  You can also find my articles on my [Google Scholar](https://scholar.google.com/citations?user=5-qU7lkAAAAJ&hl=en) page
 
 \* first author/joint first author; ^ corresponding author
 
pre-print
====

<<<<<<< HEAD
&emsp; Mireia Larrosa-Godall, Joshua XD Ang, **Philip T Leftwich**, Estela Gonzalez, Lewis Shackleford, Katherine Nevard, Rob Noad, Michelle AE Anderson, Luke Alphey. [Challenges in developing a split drive targeting dsx for the genetic control of the invasive malaria vector *Anopheles stephensi*](https://parasitesandvectors.biomedcentral.com/articles/10.1186/s13071-025-06688-0)

 <span class="__dimensions_badge_embed__" data-doi="https://doi.org/10.1186/s13071-025-06688-0" data-style="small_circle" data-hide-zero-citations="true"> <span data-badge-popover="right" data-badge-type="donut" data-doi="https://doi.org/10.1186/s13071-025-06688-0" data-hide-no-mentions="true" class="altmetric-embed"> </span>

&emsp; **Philip T Leftwich**, Jessica Purcell, Michelle Anderson, Rennos Fragkoudis, Sanjay Basu, Gareth T Lycett, Luke Alphey. [A synthetic biology approach to transgene expression](https://pubs.acs.org/doi/10.1021/acssynbio.4c00250). *ACS Synthetic Biology*

 <span class="__dimensions_badge_embed__" data-doi="https://doi.org/10.1021/acssynbio.4c00250" data-style="small_circle" data-hide-zero-citations="true"> <span data-badge-popover="right" data-badge-type="donut" data-doi="https://doi.org/10.1021/acssynbio.4c00250" data-hide-no-mentions="true" class="altmetric-embed"> </span>
 
&emsp; Angela Meccariello, Shibo Hou, Serafima Davydova, James Fawcett, [Alexandra Siddall](https://philip-leftwich.github.io/people.html#alex-siddall), **Philip T Leftwich**, Flavia Krsticevic, Philippos A Papathanos, Nikolai Windbichler.[Gene drive and genetic sex conversion in the global agricultural pest Ceratitis capitata](https://doi.org/10.1101/2023.08.16.553191). *bioRxiv*
=======
&emsp; **Philip T Leftwich**, Jessica Purcell, Michelle Anderson, Rennos Fragkoudis, Sanjay Basu, Gareth T Lycett, Luke Alphey. [A synthetic biology approach to transgene expression](https://doi.org/10.1101/2023.08.31.555539). *bioRxiv*

 <span class="__dimensions_badge_embed__" data-doi="https://doi.org/10.1101/2023.08.31.555539" data-style="small_circle" data-hide-zero-citations="true"> <span data-badge-popover="right" data-badge-type="donut" data-doi="https://doi.org/10.1101/2023.08.31.555539" data-hide-no-mentions="true" class="altmetric-embed"> </span>
>>>>>>> eb42ec3e367cee6636f07525a1f5cbdf971d0b56



2024
====

&emsp; Michelle Anderson, Estela Gonzalez, Matthew Edgington, Joshua Ang, Deepak-Kumar Purusothaman, Lewis Shackleford, Katherine Nevard, Sebald Verkuikl, Tim Harvey-Samuel, **Philip T Leftwich**, Kevin Esvelt, Luke Alphey. [A multiplexed, confinable CRISPR/Cas9 gene drive propagates in caged *Aedes aegypti* populations](https://doi.org/10.1038/s41467-024-44956-2). *Nature Communications*

<span class="__dimensions_badge_embed__" data-doi="10.1038/s41467-024-44956-2" data-style="small_circle" data-hide-zero-citations="true"> <span data-badge-popover="right" data-badge-type="donut" data-doi="10.1038/s41467-024-44956-2" data-hide-no-mentions="true" class="altmetric-embed"> </span>

2023
====

 Angela Meccariello, Shibo Hou, Serafima Davydova, James Fawcett, Alexandra Siddall,  **Philip T Leftwich**, Flavia Krsticevic, Philippos A Papathanos, Nikolai Windbichler. [Gene drive and genetic sex conversion in the global agricultural pest *Ceratitis capitata*](https://doi.org/10.1038/s41467-023-44399-1) *Nature Communications*
 
 <span class="__dimensions_badge_embed__" data-doi="10.1038/s41467-023-44399-1" data-style="small_circle" data-hide-zero-citations="true"> <span data-badge-popover="right" data-badge-type="donut" data-doi="10.1038/s41467-023-44399-1" data-hide-no-mentions="true" class="altmetric-embed"> </span>
 
 Michelle A.E. Anderson, **Philip T Leftwich**, Ray Wilson, Leonela Z Carabajal Paladino, Sanjay Basu, Sara Rooney, Zach Adelman, Luke Alphey. [AePUb promoter length modulates gene expression in *Aedes aegypti*](https://doi.org/10.1038/s41598-023-47777-3) *Scientific Reports*

<span class="__dimensions_badge_embed__" data-doi="10.1038/s41598-023-47777-3" data-style="small_circle" data-hide-zero-citations="true"> <span data-badge-popover="right" data-badge-type="donut" data-doi="10.1038/s41598-023-47777-3" data-hide-no-mentions="true" class="altmetric-embed"> </span>

 Leonela Z Carabajal Paladino, Ray Wilson, Priscilla Y.L. Tng, Vishaal Dhokiya, Elizabeth Keen, Piotr Cuber, Will Larner, Sara Rooney, Melanie Nicholls, Anastasia Uglow, Luke Williams, Michelle A.E. Anderson, Sanjay Basu, **Philip T Leftwich**, Luke Alphey. [Optimizing CRE and PhiC31 mediated recombination in *Aedes aegypti*](https://www.frontiersin.org/articles/10.3389/fbioe.2023.1254863/full) *Frontiers in Bioengineering and Biotechnology*
 
<span class="__dimensions_badge_embed__" data-doi="10.3389/fbioe.2023.1254863" data-style="small_circle" data-hide-zero-citations="true"> <span data-badge-popover="right" data-badge-type="donut" data-doi="10.3389/fbioe.2023.1254863" data-hide-no-mentions="true" class="altmetric-embed"> </span>

&emsp; Tim Harvey-Samuel, Xuechen Feng, Emily M Okamoto, Deepak-Kumar Purusothaman, **Philip T. Leftwich**, Luke Alphey, Valentino M Gantz. [CRISPR-based gene drives generate super-Mendelian inheritance in the disease vector *Culex quinquefasciatus*](https://doi.org/10.1038/s41467-023-41834-1). *Nature Communications*

<span class="__dimensions_badge_embed__" data-doi="10.1038/s41467-023-41834-1" data-style="small_circle" data-hide-zero-citations="true"> <span data-badge-popover="right" data-badge-type="donut" data-doi="10.1038/s41467-023-41834-1" data-hide-no-mentions="true" class="altmetric-embed"> </span>

&emsp; Colleen Sprigg, **Philip T Leftwich**, Emily Burton, Dawn Scholey, Michael R Bedford, Charles A Brearley. [Accentuating the positive and eliminating the negative: efficacy of TiO~2~ as digestibility index marker for poultry nutrition studies](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0284724). *Plos One - In Press*

<span class="__dimensions_badge_embed__" data-doi="10.1371/journal.pone.0284724" data-style="small_circle" data-hide-zero-citations="true"> <span data-badge-popover="right" data-badge-type="donut" data-doi="10.1371/journal.pone.0284724" data-hide-no-mentions="true" class="altmetric-embed"> </span>

2022
====

&emsp; Alex Siddall, Tim Harvey-Samuel, Tracey Chapman, **Philip T Leftwich**^. [Manipulating insect sex determination pathways for genetic pest management: opportunities and challenges](https://www.frontiersin.org/articles/10.3389/fbioe.2022.867851/abstract). *Frontiers in Biotechnology and Bioengineering*

<span class="__dimensions_badge_embed__" data-doi="10.3389/fbioe.2022.867851" data-style="small_circle" data-hide-zero-citations="true"> <span data-badge-popover="right" data-badge-type="donut" data-doi="10.3389/fbioe.2022.867851" data-hide-no-mentions="true" class="altmetric-embed"> </span>

&emsp; Darrington M, **Leftwich PT**\*, Holmes NA, Friend LA, Clarke NVE, Worsley SF, Margaritopolous JT, Hogenhout SA, Hutchings MI, Chapman T. [Characterisation of the symbionts in the Mediterranean fruitfly gut](https://doi.org/10.1099/mgen.0.000801). *Microbial Genomics* 
<span class="__dimensions_badge_embed__" data-doi="10.1099/mgen.0.000801" data-style="small_circle" data-hide-zero-citations="true"> <span data-badge-popover="right" data-badge-type="donut" data-doi="10.1099/mgen.0.000801" data-hide-no-mentions="true" class="altmetric-embed"> </span>

&emsp;Xuejiao Xu, Tim Harvey-Samuel, Hamid Anees Siddiqui, Joshua Ang, Michelle E Anderson, Christine Reitmayer, Erica Lovett, **Philip T Leftwich**, Minsheng You, Luke Alphey . [Towards CRISPR/Cas9-based gene drive in the diamondback moth *Plutella xylostella*](https://doi.org/10.1089/crispr.2021.0129). *The CRISPR Journal* 
<span class="__dimensions_badge_embed__" data-doi="10.1089/crispr.2021.0129" data-style="small_circle" data-hide-zero-citations="true"> <span data-badge-popover="right" data-badge-type="donut" data-doi="10.1089/crispr.2021.0129" data-hide-no-mentions="true" class="altmetric-embed"> </span>
  
2021
====

&emsp; Benjamin J Tully, Joy Buongiorno, Ashley Brooke Cohen, Jacob A Cram, Arkadiy I Garber, Sarah K Hu, Arianna I Krinos, **Philip T Leftwich**, Alexis Marshall, Ella T Sieradzki, Daan R Speth, Elizabeth A Suter, Christopher B Trivedi, Luis E Valentin-Alvarado, Jake L Weissman, Michael D Lee, Harriet Alexander, R Eric Collins, Maria Pachiadaki, Adelaide CE Rhodes, Wayne Decatur [The Bioinformatics Virtual Coordination Network: an open-source and interactive learning environment](https://www.frontiersin.org/articles/10.3389/feduc.2021.711618/abstract). *Frontiers in Education*
<span class="__dimensions_badge_embed__" data-doi="10.3389/feduc.2021.711618" data-style="small_circle" data-hide-zero-citations="true"> <span data-badge-popover="right" data-badge-type="donut" data-doi="10.3389/feduc.2021.711618" data-hide-no-mentions="true" class="altmetric-embed"> </span>
  
&emsp; Harvey-Samuel TD, Xu X, Lovett E, Dafa’alla T, Walker A, Norman VC,Carter R, Teal J, Akilan L, **Leftwich PT**, Reitmayer CM, Siddiqui HA, Alphey, L. [Engineered
expression of the invertebrate-specific scorpion toxin AaHIT reduces adult longevity and female fecundity in the diamondback moth Plutella xylostella](https://doi.org/10.1002/ps.6353). *Pest Management Science* 
<span class="__dimensions_badge_embed__" data-doi="10.1002/ps.6353" data-style="small_circle" data-hide-zero-citations="true"> <span data-badge-popover="right" data-badge-type="donut" data-doi="10.1002/ps.6353" data-hide-no-mentions="true" class="altmetric-embed"> </span>

&emsp; **Philip T Leftwich**\*^, Lewis G Spurgin, Tim Harvey-Samuel, Callum Thomas, Leonela Carabajal Paladino, Matthew P. Edgington, Luke S Alphey. [Genetic pest management and the background genetics of release strains]( 
https://royalsocietypublishing.org/doi/10.1098/rstb.2019.0805). *Philosophical Transactions of the Royal Society B*
<span class="__dimensions_badge_embed__" data-doi="10.1098/rstb.2019.0805" data-style="small_circle" data-hide-zero-citations="true"> <span data-badge-popover="right" data-badge-type="donut" data-doi="10.1098/rstb.2019.0805 " data-hide-no-mentions="true" class="altmetric-embed"> </span>
  
2020
====

&emsp; **Philip T Leftwich**\*^, Matthew Edgington, Tracey Chapman. [Transmission efficiency drives host-microbe associations](https://royalsocietypublishing.org/doi/10.1098/rspb.2020.0820). *Proceedings of the Royal Society B*
<span class="__dimensions_badge_embed__" data-doi="10.1098/rspb.2020.0820" data-style="small_circle" data-hide-zero-citations="true"> <span data-badge-popover="right" data-badge-type="donut" data-doi="10.1098/rspb.2020.0820" data-hide-no-mentions="true" class="altmetric-embed"> </span>

&emsp; Priscilla YL Tng, Leonela Carabajal Paladino, Sebald Verkuijl, Jessica Purcell, **Philip T Leftwich**, Rennos Fragkoudis, Rob Noad, Luke Alphey. [Cas13b-dependent and -independent RNA knockdown of viral sequences in mosquito cells following guide RNA expression](https://www.nature.com/articles/s42003-020-01142-6). *Communications Biology* 
<span class="__dimensions_badge_embed__" data-doi="10.1038/s42003-020-01142-6" data-style="small_circle" data-hide-zero-citations="true"> <span data-badge-popover="right" data-badge-type="donut" data-doi="10.1038/s42003-020-01142-6" data-hide-no-mentions="true" class="altmetric-embed"> </span>

&emsp; Michelle AE Anderson, Jessica Purcell, Sebald AN Verkuijl, Victoria C Norman, **Philip T Leftwich**, Tim Harvey-Samuel, Luke S Alphey. [Expanding the CRISPR Toolbox in Culicine Mosquitoes: In Vitro Validation of Pol III Promoters](https://pubs.acs.org/doi/abs/10.1021/acssynbio.9b00436). *ACS Synthetic Biology*
<span class="__dimensions_badge_embed__" data-doi="10.1021/acssynbio.9b00436" data-style="small_circle" data-hide-zero-citations="true"> <span data-badge-popover="right" data-badge-type="donut" data-doi="10.1021/acssynbio.9b00436" data-hide-no-mentions="true" class="altmetric-embed"> </span>

2019
====

&emsp; KH Redford, TM Brooks, NBW Macfarlane, JS Adams, Luke Alphey, Elizabeth Bennet, Jason Delborne, Hilde Eggermont, Kevin Esvelt, Ann Kingirl, Adam Kokotovich, Bartomiej Kolodziejczyk, Todd Kuiken, Aroha Mead, Maria Oliva, Edward Perello, Lydia Slobodian, Delphine Thizy, Daniel Tompkins, Gerd Winter, Karl Campbell, Johanna Elsensohn, Nick Holmes, Chris Farmer, Bradford Keitt, **Philip Leftwich**, Tom Maloney, Daniel Masiga, Andrew Newhouse, Ben Novak, Ryan Phelan, William Powell, Louise Rollins-Smith, Madeline van Oppen. [Genetic frontiers for conservation : an assessment of synthetic biology and biodiversity conservation : technical assessment](https://portals.iucn.org/library/node/48408). *IUCN*
<span class="__dimensions_badge_embed__" data-doi="10.2305/IUCN.CH.2019.05.en" data-style="small_circle" data-hide-zero-citations="true"> <span data-badge-popover="right" data-badge-type="donut" data-doi="10.2305/IUCN.CH.2019.05.en" data-hide-no-mentions="true" class="altmetric-embed"> </span>

&emsp; **PT Leftwich**\*, WJ Nash, LA Friend, T Chapman. [Contribution of maternal effects to dietary selection in Mediterranean fruit flies](https://onlinelibrary.wiley.com/doi/full/10.1111/evo.13664). *Evolution*
<span class="__dimensions_badge_embed__" data-doi="10.1111/evo.13664" data-style="small_circle" data-hide-zero-citations="true"> <span data-badge-popover="right" data-badge-type="donut" data-doi="10.1111/evo.13664" data-hide-no-mentions="true" class="altmetric-embed"> </span>

2018
====

&emsp; **Philip T Leftwich**\*, Matthew P Edgington, Tim Harvey-Samuel, Leonela Z Carabajal Paladino, Victoria C Norman, Luke Alphey. [Recent advances in threshold-dependent gene drives for mosquitoes](https://portlandpress.com/biochemsoctrans/article/46/5/1203/67820/Recent-advances-in-threshold-dependent-gene-drives). *Biochemical Society Transactions*
<span class="__dimensions_badge_embed__" data-doi="10.1042/BST20180076" data-style="small_circle" data-hide-zero-citations="true"> <span data-badge-popover="right" data-badge-type="donut" data-doi="10.1042/BST20180076" data-hide-no-mentions="true" class="altmetric-embed"> </span>

&emsp; **Philip T Leftwich**\*, Matt Hutchings, Tracey Chapman. [Diet, Gut Microbes and Host Mate Choice: Understanding the significance of microbiome effects on host mate choice requires a case by case evaluation](https://onlinelibrary.wiley.com/doi/abs/10.1002/bies.201800053@10.1002/(ISSN)1521-1878.microbiome). *Bio-Essays*
<span class="__dimensions_badge_embed__" data-doi="10.1002/bies.201800053" data-style="small_circle" data-hide-zero-citations="true"> <span data-badge-popover="right" data-badge-type="donut" data-doi="10.1002/bies.201800053" data-hide-no-mentions="true" class="altmetric-embed"> </span>

&emsp; **Philip T Leftwich**\*^ and Tracey Chapman. [Testing for Assortative Mating by Diet in Drosophila melanogaster](https://bio-protocol.org/e3057). *Bio-Protocol*
<span class="__dimensions_badge_embed__" data-doi="10.21769/BioProtoc.3057" data-style="small_circle" data-hide-zero-citations="true"> <span data-badge-popover="right" data-badge-type="donut" data-doi="10.21769/BioProtoc.3057" data-hide-no-mentions="true" class="altmetric-embed"> </span>
  
&emsp; **Philip T Leftwich**\*, Naomi V. E. Clarke, Matthew I. Hutchings, Tracey Chapman. [Gut microbiomes and reproductive isolation in Drosophila](https://doi.org/10.1073/pnas.1708345114). *PNAS* 
<span class="__dimensions_badge_embed__" data-doi="10.1073/pnas.1708345114" data-style="small_circle" data-hide-zero-citations="true"> <span data-badge-popover="right" data-badge-type="donut" data-doi="10.1073/pnas.1708345114" data-hide-no-mentions="true" class="altmetric-embed"> </span>

&emsp; **Philip T Leftwich**\*, Naomi V. E. Clarke, Matthew I. Hutchings, Tracey Chapman. [Reply to Rosenberg et al.: Diet, gut bacteria, and assortative mating in Drosophila melanogaster](https://www.pnas.org/content/115/10/E2154). *PNAS*
<span class="__dimensions_badge_embed__" data-doi="10.1073/pnas.1721804115" data-style="small_circle" data-hide-zero-citations="true"> <span data-badge-popover="right" data-badge-type="donut" data-doi="10.1073/pnas.1721804115" data-hide-no-mentions="true" class="altmetric-embed"> </span>

&emsp; **Philip T Leftwich**\*, Naomi V. E. Clarke, Matthew I. Hutchings, Tracey Chapman. [Reply to Obadia et al.: Effect of methyl paraben on host–microbiota interactions in Drosophila melanogaster](https://www.pnas.org/content/115/20/E4549). *PNAS*
<span class="__dimensions_badge_embed__" data-doi="10.1073/pnas.1805499115" data-style="small_circle" data-hide-zero-citations="true"> <span data-badge-popover="right" data-badge-type="donut" data-doi="10.1073/pnas.1805499115" data-hide-no-mentions="true" class="altmetric-embed"> </span>

2017
====
&emsp; **Philip T Leftwich**\*, William J Nash, Lucy A Friend, Tracey Chapman. [Adaptation to divergent larval diets in the medfly, *Ceratitis capitata*](https://onlinelibrary.wiley.com/doi/full/10.1111/evo.13113). *Evolution*
<span class="__dimensions_badge_embed__" data-doi="10.1111/evo.13113" data-style="small_circle" data-hide-zero-citations="true"> <span data-badge-popover="right" data-badge-type="donut" data-doi="10.1111/evo.13113" data-hide-no-mentions="true" class="altmetric-embed"> </span>

&emsp; Ben Longdon, Jonathan P Day, Nora Schulz, **Philip T Leftwich**, Maaike A de Jong, Casper J Breuker, Melanie Gibbs, Darren J Obbard, Lena Wilfert, Sophia CL Smith, John E McGonigle, Thomas M Houslay, Lucy I Wright, Luca Livraghi, Luke C Evans, Lucy A Friend, Tracey Chapman, John Vontas, Natasa Kambouraki, Francis M Jiggins. [Vertically transmitted rhabdoviruses are found across three insect families and have dynamic interactions with their hosts](https://royalsocietypublishing.org/doi/full/10.1098/rspb.2016.2381). *Proceedings of the Royal Society B*
<span class="__dimensions_badge_embed__" data-doi="10.1098/rspb.2016.2381" data-style="small_circle" data-hide-zero-citations="true"> <span data-badge-popover="right" data-badge-type="donut" data-doi="10.1098/rspb.2016.2381" data-hide-no-mentions="true" class="altmetric-embed"> </span>

2016
====
&emsp; **PT Leftwich**\*, M Bolton, T Chapman. [Evolutionary biology and genetic techniques for insect control](https://doi.org/10.1111/eva.12280). *Evolutionary Applications* 
<span class="__dimensions_badge_embed__" data-pmid="27087849" data-style="small_circle" data-hide-zero-citations="true"> <span data-badge-popover="right" data-badge-type="donut" data-doi="https://doi.org/10.1111/eva.12280" data-hide-no-mentions="true" class="altmetric-embed"> </span> 

2014
=====
&emsp; **Philip T Leftwich**\*, Martha Koukidou, Polychronis Rempoulakis, Hong-Fei Gong, Antigoni Zacharopoulou, Guoliang Fu, Tracey Chapman, Aris Economopoulos, John Vontas, Luke Alphey. [Genetic elimination of field-cage populations of Mediterranean fruit flies](https://doi.org/10.1098/rspb.2014.1372). *Proceedings of the Royal Society B*  
 <span class="__dimensions_badge_embed__" data-doi="10.1098/rspb.2014.1372" data-style="small_circle" data-hide-zero-citations="true"><span data-badge-popover="right" data-badge-type="donut" data-doi="https://doi.org/10.1098/rspb.2014.1372" data-hide-no-mentions="true" class="altmetric-embed"> </span>

2012
======
&emsp; **PT Leftwich**\*, DA Edward, L Alphey, MJG Gage, T Chapman. [Variation in adult sex ratio alters the association between courtship, mating frequency and paternity in the lek‐forming fruitfly *Ceratitis capitata*](https://doi.org/10.1111/j.1420-9101.2012.02556.x). *Journal of Evolutionary Biology* 
<span class="__dimensions_badge_embed__" data-doi="10.1111/j.1420-9101.2012.02556.x" data-style="small_circle" data-hide-zero-citations="true"> <span data-badge-popover="right" data-badge-type="donut" data-doi="10.1111/j.1420-9101.2012.02556.x" data-hide-no-mentions="true" class="altmetric-embed"> </span>

<script type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>
<script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>



